### PR TITLE
Huy/server

### PR DESCRIPTION
**Pull request by huyqbui**
Get and post routes working finally!

Database table has 10 columns:
    id, (bigint) <-- PRIMARY KEY -- number
    title, (varchar) -- string
    location, (varchar) -- string
    video_url, (varchar) -- string
    image_url, (varchar) -- string
    username, (varchar) -- string
    photo, (varchar) -- string
    email, (varchar) -- string
    details, (varchar) -- string
    time (varchar) -- string

### CODE REVIEW

**Comment by Ruzeb** [comment]
> Get and post routes working finally!
> 
> Database table has 10 columns: id, (bigint) <-- PRIMARY KEY -- number title, (varchar) -- string location, (varchar) -- string video_url, (varchar) -- string image_url, (varchar) -- string username, (varchar) -- string photo, (varchar) -- string email, (varchar) -- string details, (varchar) -- string time (varchar) -- string

i like this information

**Review by chloelu29 — APPROVED** [review]
Amazing Huy!!

**Comment by Ruzeb** [comment]
Are we doing user functionality in our app? 
If we are, I wouldn't put the username and email in the incident table, but in a separate table, and then join them on the foreign key user_id

**Review by Ruzeb — CHANGES_REQUESTED** [review]
Are we doing user functionality in our app?
If we are, I wouldn't put the username and email in the incident table, but in a separate table, and then join them on the foreign key user_id
Also, shouldn't the table be called 'incidents' instead of user. It's not that important but it would make more sense when we create another table called 'user' for the actual userinfo

@huyqbui @chloelu29

**Comment by huyqbui** [comment]
For sure, that sounds good to me! I’m heading out of town for the rest of
the day, but tomorrow I can work on editing this table to be incidents and
then create a user table as well!

-Huy

**Comment by Ruzeb** [comment]
We don’t have to close the pull request because Huy will add changes to this one, and then we can approve it.

**Comment by chloelu29** [comment]
Sorry I thought I have to close his to push mine I'm reopening it now

**Comment by huyqbui** [comment]
Edited the db tables. We now have a public.user table and public.incident table:
Configured routes to be able to get public.incident rows by street name.

Ex. say the endpoint is '/incidents/location/:name'
name could be a street name, city, state, or zipcode, and they should all find rows that contain those characters

  table public.incident:
    {
        "incident_id": 1, <-- PRIMARY KEY
        "title": "title here",
        "street_name": "street name, city, state zipcode",
        "video_url": "video url here"
        "image_url": "image url here"
        "details": "details here"
        "time": "1/2/2022, 10:11:08 PM",
        "user_id": 1, <-- FOREIGN KEY for public.user
        "location_id": 1 <-- FOREIGN KEY for public.location
    },

  table public.user:
    {
        "user_id": 1, <-- PRIMARY KEY
        "name": "Huy Bui",
        "email": "shuyttea@gmail.com",
        "photo": "https://avatars.githubusercontent.com/u/94398519?s=40&v=4",
        "password": "string here"
    },

(There's also a public.location table, but I don't think we'll need it yet)

**Review by Ruzeb — APPROVED** [review]
Clean code, clean information about what your feature does, and good design of future features

**Pull request merged**
